package com.example.k234112e_hqv;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.ImageButton;
import android.widget.TextView;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.RecyclerView;

import com.example.adapters.CustomerOrderAdapter;
import com.example.models.Order;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;

import java.util.ArrayList;
import java.util.List;

public class CustomerOrdersActivity extends AppCompatActivity {

    private ImageButton btnOrdersBack;
    private RecyclerView rvOrders;
    private TextView txtEmptyOrders;

    private List<Order> orderList = new ArrayList<>();
    private CustomerOrderAdapter orderAdapter;

    private FirebaseDatabase database;
    private DatabaseReference ordersRef;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_customer_orders);

        initViews();
        setupFirebase();
        setupRecyclerView();
        loadOrders();
    }

    private void initViews() {
        btnOrdersBack = findViewById(R.id.btnOrdersBack);
        rvOrders = findViewById(R.id.rvOrders);
        txtEmptyOrders = findViewById(R.id.txtEmptyOrders);

        btnOrdersBack.setOnClickListener(v -> finish());
    }

    private void setupFirebase() {
        database = FirebaseDatabase.getInstance("https://k234112e-default-rtdb.asia-southeast1.firebasedatabase.app/");
        ordersRef = database.getReference("orders");
    }

    private void setupRecyclerView() {
        orderAdapter = new CustomerOrderAdapter(orderList, order -> {
            Intent intent = new Intent(CustomerOrdersActivity.this, CustomerOrderDetailActivity.class);
            intent.putExtra("ORDER_ID", order.getOrderId());
            startActivity(intent);
        });
        rvOrders.setAdapter(orderAdapter);
    }

    private void loadOrders() {
        // Query orders equal to customerId "CUST001"
        ordersRef.orderByChild("customerId").equalTo("CUST001")
                .addValueEventListener(new ValueEventListener() {
                    @Override
                    public void onDataChange(@NonNull DataSnapshot dataSnapshot) {
                        orderList.clear();
                        for (DataSnapshot snapshot : dataSnapshot.getChildren()) {
                            Order order = snapshot.getValue(Order.class);
                            if (order != null) {
                                order.setOrderId(snapshot.getKey());
                                orderList.add(order);
                            }
                        }
                        // Sort orders: new orders on top
                        // Since IDs are generated by push key, sorting by key or date can work.
                        // Let's sort by date/ID descending
                        orderList.sort((o1, o2) -> {
                            String d1 = o1.getOrderDateString() != null ? o1.getOrderDateString() : "";
                            String d2 = o2.getOrderDateString() != null ? o2.getOrderDateString() : "";
                            return d2.compareTo(d1);
                        });

                        orderAdapter.notifyDataSetChanged();

                        if (orderList.isEmpty()) {
                            txtEmptyOrders.setVisibility(View.VISIBLE);
                            rvOrders.setVisibility(View.GONE);
                        } else {
                            txtEmptyOrders.setVisibility(View.GONE);
                            rvOrders.setVisibility(View.VISIBLE);
                        }
                    }

                    @Override
                    public void onCancelled(@NonNull DatabaseError databaseError) {
                        Toast.makeText(CustomerOrdersActivity.this, "Failed to load orders: " + databaseError.getMessage(), Toast.LENGTH_SHORT).show();
                    }
                });
    }
}
